/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "focusdir.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "swapfocus.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"
