#!/bin/sh
export QT_QPA_PLATFORMTHEME=gtk2
export LC_ALL="en_US.UTF-8"
export PATH="${PATH}:${HOME}/.local/bin"
export QT_STYLE_OVERRIDE=gtk2
# export gtk-application-prefer-dark-theme = true
export _GTK_THEME_VARIANT=dark
export _JAVA_AWT_WM_NONREPARENTING=1
# picom --experimental-backends --blur-method dual_kawase &
xrdb ~/.Xresources
#wal -i ~/git/walls/fightclub.jpeg &
nitrogen --restore &
# feh --bg-fill --randomize /home/gs/walls
xbindkeys &
sxhkd &
xinput --set-prop 12 'libinput Accel Speed' -0.7 &
dunst -conf ~/.cache/wal/dunstrc &
# qbittorrent &
flameshot &
mpdas &
mpd &
mpDris2 &
slstatus &
nm-applet &
volctl &
xinput float 15 &
copyq &
lxqt-powermanagement &
exec dwm 2> ~/dwm.log
